version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=mediar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
        test: "exit 0"

  mediar:
    restart: always
    build: .
    container_name: mediar
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    environment:
      - PORTNGINX=8080
    restart: always
    build:
      context: ./nginx
    container_name: nginx

    depends_on:
      - mediar
    ports:
      - "81:81"
